In [1]:
import numpy as np


In [2]:
type(np) # type to check the nature 

module

In [11]:
l = [1,2,3,4,5]

In [12]:
arr =np.array(l) # call using the module

In [15]:
type(arr)

numpy.ndarray

In [16]:
print(arr) # print the list 

[1 2 3 4 5]


In [17]:
arr # gives output of the value as a default

array([1, 2, 3, 4, 5])

# play with numpy

In [38]:
dir(arr) # dir to see all builtin names 


['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [29]:
arr = np.arange(0,10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr = np.zeros(7) 
print(arr)

[0. 0. 0. 0. 0. 0. 0.]


In [37]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

In [41]:
np.random.randint(1,100,(2,2))
# 1 to 100 as range 
# (2,2) as Dimensions

array([[13, 66],
       [61, 21]])

In [46]:
who = np.random.choice(['styam','ronaldo','obit'],1) # choose any one 
print(who)

['ronaldo']


In [53]:
n = np.random.randint(1 , 100,50)
print(n)

[75 54 19  5 87 42 55 71 95 44 83 45 96 67 77 73 35 94 29  5 27  1 13 11
 66 55 98 21 34 64 90 28 32 68 28 68 76 48 48 92 46 39 77  5 59 12 35 38
  3 19]


In [54]:
n + 4

array([ 79,  58,  23,   9,  91,  46,  59,  75,  99,  48,  87,  49, 100,
        71,  81,  77,  39,  98,  33,   9,  31,   5,  17,  15,  70,  59,
       102,  25,  38,  68,  94,  32,  36,  72,  32,  72,  80,  52,  52,
        96,  50,  43,  81,   9,  63,  16,  39,  42,   7,  23])

In [55]:
n*5

array([375, 270,  95,  25, 435, 210, 275, 355, 475, 220, 415, 225, 480,
       335, 385, 365, 175, 470, 145,  25, 135,   5,  65,  55, 330, 275,
       490, 105, 170, 320, 450, 140, 160, 340, 140, 340, 380, 240, 240,
       460, 230, 195, 385,  25, 295,  60, 175, 190,  15,  95])

In [56]:
n /2

array([37.5, 27. ,  9.5,  2.5, 43.5, 21. , 27.5, 35.5, 47.5, 22. , 41.5,
       22.5, 48. , 33.5, 38.5, 36.5, 17.5, 47. , 14.5,  2.5, 13.5,  0.5,
        6.5,  5.5, 33. , 27.5, 49. , 10.5, 17. , 32. , 45. , 14. , 16. ,
       34. , 14. , 34. , 38. , 24. , 24. , 46. , 23. , 19.5, 38.5,  2.5,
       29.5,  6. , 17.5, 19. ,  1.5,  9.5])

In [57]:
n//4

array([18, 13,  4,  1, 21, 10, 13, 17, 23, 11, 20, 11, 24, 16, 19, 18,  8,
       23,  7,  1,  6,  0,  3,  2, 16, 13, 24,  5,  8, 16, 22,  7,  8, 17,
        7, 17, 19, 12, 12, 23, 11,  9, 19,  1, 14,  3,  8,  9,  0,  4])

In [58]:
n%4

array([3, 2, 3, 1, 3, 2, 3, 3, 3, 0, 3, 1, 0, 3, 1, 1, 3, 2, 1, 1, 3, 1,
       1, 3, 2, 3, 2, 1, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 1, 1,
       3, 0, 3, 2, 3, 3])

In [59]:
n -7

array([68, 47, 12, -2, 80, 35, 48, 64, 88, 37, 76, 38, 89, 60, 70, 66, 28,
       87, 22, -2, 20, -6,  6,  4, 59, 48, 91, 14, 27, 57, 83, 21, 25, 61,
       21, 61, 69, 41, 41, 85, 39, 32, 70, -2, 52,  5, 28, 31, -4, 12])

In [62]:
np.sin(n) # can be use for Mathematical operation

array([-0.38778164, -0.55878905,  0.14987721, -0.95892427, -0.82181784,
       -0.91652155, -0.99975517,  0.95105465,  0.68326171,  0.01770193,
        0.96836446,  0.85090352,  0.98358775, -0.85551998,  0.99952016,
       -0.67677196, -0.42818267, -0.24525199, -0.66363388, -0.95892427,
        0.95637593,  0.84147098,  0.42016704, -0.99999021, -0.02655115,
       -0.99975517, -0.57338187,  0.83665564,  0.52908269,  0.92002604,
        0.89399666,  0.27090579,  0.55142668, -0.89792768,  0.27090579,
       -0.89792768,  0.56610764, -0.76825466, -0.76825466, -0.77946607,
        0.90178835,  0.96379539,  0.99952016, -0.95892427,  0.63673801,
       -0.53657292, -0.42818267,  0.29636858,  0.14112001,  0.14987721])

In [63]:
np.cos(n)

array([ 0.92175127, -0.82930983,  0.98870462,  0.28366219,  0.56975033,
       -0.39998531,  0.02212676, -0.30902273,  0.73017356,  0.99984331,
        0.24954012,  0.52532199, -0.18043045, -0.5177698 , -0.03097503,
       -0.73619272, -0.90369221,  0.96945937, -0.74805753,  0.28366219,
       -0.29213881,  0.54030231,  0.90744678,  0.0044257 , -0.99964746,
        0.02212676, -0.81928825, -0.54772926, -0.84857027,  0.39185723,
       -0.44807362, -0.96260587,  0.83422336,  0.44014302, -0.96260587,
        0.44014302,  0.82433133, -0.64014434, -0.64014434, -0.62644445,
       -0.43217794,  0.26664293, -0.03097503,  0.28366219, -0.77108022,
        0.84385396, -0.90369221,  0.95507364, -0.9899925 ,  0.98870462])

In [64]:
np.log(n)

array([4.31748811, 3.98898405, 2.94443898, 1.60943791, 4.46590812,
       3.73766962, 4.00733319, 4.26267988, 4.55387689, 3.78418963,
       4.41884061, 3.80666249, 4.56434819, 4.20469262, 4.34380542,
       4.29045944, 3.55534806, 4.54329478, 3.36729583, 1.60943791,
       3.29583687, 0.        , 2.56494936, 2.39789527, 4.18965474,
       4.00733319, 4.58496748, 3.04452244, 3.52636052, 4.15888308,
       4.49980967, 3.33220451, 3.4657359 , 4.21950771, 3.33220451,
       4.21950771, 4.33073334, 3.87120101, 3.87120101, 4.52178858,
       3.8286414 , 3.66356165, 4.34380542, 1.60943791, 4.07753744,
       2.48490665, 3.55534806, 3.63758616, 1.09861229, 2.94443898])

In [66]:
np.std(n)

28.490672157743138

In [67]:
np.mean(n)

49.04

In [71]:
np.max(n)

98

In [73]:
n[:4] # till 4th index

array([75, 54, 19,  5])

In [74]:
n[4:] # from 4th index 

array([87, 42, 55, 71, 95, 44, 83, 45, 96, 67, 77, 73, 35, 94, 29,  5, 27,
        1, 13, 11, 66, 55, 98, 21, 34, 64, 90, 28, 32, 68, 28, 68, 76, 48,
       48, 92, 46, 39, 77,  5, 59, 12, 35, 38,  3, 19])